### ISSUE TITLE
Would be cool if one could type check the indicies too

### ISSUE THREAD

**Issue by ComLock** [scub45t3v3/TypeArray#17]
For some reason js basically allows any index that can be converted to a string. Like "-1" or even "undefined".
Would be nice to say, I only allow positive integers

**Comment by scub45t3v3** [comment]
Hi @ComLock,

This is by design in JS.
Since an Array is an Object and needs to contain properties like **length**.

This library only does type validation on **valid integer keys > 0**.
This was intentional to keep the open ability for you to add and access any additional properties without the validation interfering.

If you have an example of how you would achieve what you are suggesting please feel free to open a PR.
